package com.FiftyOneDegree.research.FiftyOneDegreeCode;

public class DeviceData {

        //    public string PackageName { get; set; }
        //    public string ImeiNumber { get; set; }
        //    public string TacCode { get; set; }
        //    public string Manufacturer { get; set; }
        //    public string Model { get; set; }
        //    public int? Version { get; set; }
        //    public string ScreenResolution { get; set; }
        //    public int? Dpi { get; set; }
        //    public string SerialNumber { get; set; }
        //    public string Board { get; set; }
        //    public string Brand { get; set; }
        //    public string DeviceName { get; set; }
        //    public string DisplayBuildId { get; set; }
        //    public string Fingerprint { get; set; }
        //    public string Hardware { get; set; }
        //    public string Host { get; set; }
        //    public string LableId { get; set; }
        //    public string Product { get; set; }
        //    public string RadioFirmwareNumber { get; set; }
        //    public string BuildTags { get; set; }
        //    public long? Times { get; set; }
        //    public string BuildType { get; set; }
        //    public string User { get; set; }
        //    public string UserAgentSystem { get; set; }
        //    public string UserAgentWebView { get; set; }
        //    public string CurrentBatteryCharge { get; set; }
        //    public double? BackCameraMegaPixels { get; set; }
        //    public string CameraTypes { get; set; }
        //    public double? FrontCameraMegaPixels { get; set; }
        //    public bool? HasCamera { get; set; }
        //    public bool? HasNFC { get; set; }
        //    public bool? SupportsPhoneCalls { get; set; }
        //    public string DeviceType { get; set; }
        //    public bool? IsMobile { get; set; }
        //    public bool? IsSmallScreen { get; set; }
        //    public bool? IsSmartPhone { get; set; }
        //    public bool? IsTablet { get; set; }
        //    public long? DeviceRAM { get; set; }
        //    public string MaxInternalStorage { get; set; }
        //    public string HardwareFamily { get; set; }
        //    public string HardwareModel { get; set; }
        //    public string HardwareModelVariants { get; set; }
        //    public string HardwareName { get; set; }
        //    public string HardwareVendor { get; set; }
        //    public string Oem { get; set; }
        //    public string NativeBrand { get; set; }
        //    public string NativeDevice { get; set; }
        //    public string NativeModel { get; set; }
        //    public string Cpu { get; set; }
        //    public int? CpuCores { get; set; }
        //    public string CpuDesigner { get; set; }
        //    public string CpuMaximumFrequency { get; set; }
        //    public string SoC { get; set; }
        //    public double? ScreenInchesDiagonal { get; set; }
        //    public int? ScreenInchesDiagonalRounded { get; set; }
        //    public double? ScreenInchesHeight { get; set; }
        //    public int? ScreenInchesSquare { get; set; }
        //    public double? ScreenInchesWidth { get; set; }
        //    public double? ScreenMMDiagonal { get; set; }
        //    public int? ScreenMMDiagonalRounded { get; set; }
        //    public double? ScreenMMHeight { get; set; }
        //    public int? ScreenMMSquare { get; set; }
        //    public double? ScreenMMWidth { get; set; }
        //    public int? ScreenPixelsHeight { get; set; }
        //    public int? ScreenPixelsWidth { get; set; }
        //    public string SupportedSensorTypes { get; set; }
        //    public int? MaxNumberOfSIMCards { get; set; }
        //    public int? OnPowerConsumption { get; set; }
        //    public int? RefreshRate { get; set; }
        //    public string PublicIP { get; set; }
        //    public int? MccNetwork { get; set; }
        //    public int? MncNetwork { get; set; }
        //    public int? MccSIM { get; set; }
        //    public int? MncSIM { get; set; }
        //    public double? Latitude { get; set; }
        //    public double? Longitude { get; set; }
        //    public string PublicIPOfWebRequest { get; set; }
        //    public string HttpHeaders { get; set; }
        //    public string ConnectivityType { get; set; }
        //    public string NetworkType { get; set; }

}
